### PR TITLE
Added byte decoding when processing arrays

### PR DESCRIPTION
**Pull request by elvioaruta**
- Fixes process_array (when using /diagnostics in gz-docker-2.db3 as example)
Demo (you can see there's data being sent to "/inorbit/diagnostics_test" ) : 
image

### CODE REVIEW

**Comment by elvioaruta** [comment]
Note: json.dumps doesn't work for byte values

**Comment by adamantivm** [comment]
Ugh, ok. Then we should do this everywhere that we do json.dumps(). There is another instance of this in MAPPING_TYPE_JSON_OF_FIELDS.

I suggest you create a new small function "safe_json_dump" or something like that where you do this trick, and then replace the calls to json.dumps to use this new function.

**Comment by adamantivm** [comment]
@elvioaruta I found a better solution.

From the python docs:

image

So now it works. We can add more support to it over time.

**Comment by elvioaruta** [comment]
> @elvioaruta I found a better solution.
> 
> From the python docs:
> 
> image
> 
> So now it works. We can add more support to it over time.

GJ, nice one!

**Pull request merged**
